{% set name = "pynndescent" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43d390ae80793f4c1f8a8096b4ebab4186c3a9c378f7214975480105257ffb4b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - setuptools
    - numpy >=1.13
    - numba >=0.45
    - scikit-learn >=0.19
    - scipy >=1.0

test:
  requires:
    - python
    - setuptools
  commands:
    - python -c "import pkg_resources; pkg_resources.require('pynndescent')"
  imports:
    - pynndescent

about:
  home: http://github.com/lmcinnes/pynndescent
  license: BSD-2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Simple fast approximate nearest neighbor search'

  description: |
    A Python nearest neighbor descent for approximate nearest neighbors. 
    This is a relatively straightforward python implementation of 
    Nearest Neighbor Descent for k-neighbor-graph construction and 
    approximate nearest neighbor search.
  dev_url: https://github.com/lmcinnes/pynndescent

extra:
  recipe-maintainers:
    - lmcinnes
